# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "feat-ghactions" ]
    tags: [ "v*.*.*"]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish
    - name: Prepare Artifact
      shell: pwsh
      run: |
        Echo $env:GITHUB_WORKSPACE
        New-Item $env:GITHUB_WORKSPACE\Packaging\ -Type Directory -ea 0
        Copy-Item -Path $env:GITHUB_WORKSPACE\uewhere\bin\Release\net8.0-windows\win-x64\publish\uewhere.exe -Destination $env:GITHUB_WORKSPACE\Packaging\uewhere.exe
        Copy-Item -Path $env:GITHUB_WORKSPACE\uaterry\bin\Release\net8.0-windows\win-x64\publish\uaterry.exe -Destination $env:GITHUB_WORKSPACE\Packaging\uaterry.exe
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          .\Packaging\
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          $env:GITHUB_WORKSPACE\Packaging\uewhere.exe
          $env:GITHUB_WORKSPACE\Packaging\uaterry.exe
